import { AirlineId, AirlineInfo } from './types';

export const AIRLINE_DIRECTORY: Record<AirlineId, AirlineInfo> = {
  indigo: {
    id: 'indigo',
    name: 'IndiGo (InterGlobe Aviation Ltd)',
    code: '6E',
    tagline: "India's largest low-cost carrier with on-time performance focus",
    logoBg: 'bg-blue-600',
    brandColor: '#001b94',
    officialCocUrl: 'https://www.goindigo.in/information/conditions-of-carriage.html',
    officialCharterUrl: 'https://www.goindigo.in/information/passenger-charter.html',
    officialSupportUrl: 'https://www.goindigo.in/contact-us.html',
    nodalOfficer: {
      name: 'Nodal Grievance Officer',
      email: 'nodalofficer@goindigo.in',
      phone: '+91 124 6173838',
      address: 'Central Wing, Ground Floor, Thapar House, 124, Janpath, New Delhi - 110001, India',
      turnaround: 'Resolution within 10 business days',
    },
    appellateAuthority: {
      name: 'Appellate Authority for Passenger Grievances',
      email: 'appellateauthority@goindigo.in',
      phone: '+91 124 6173838',
      turnaround: 'Final appeal decision within 30 business days',
    },
    customerCare: {
      phone: '+91 9910 383838 / 0124-6173838',
      email: 'customer.relations@goindigo.in',
      chatUrl: 'https://www.goindigo.in/contact-us.html',
    },
  },
  airindia: {
    id: 'airindia',
    name: 'Air India',
    code: 'AI',
    tagline: 'Flag carrier full-service airline (Tata Group)',
    logoBg: 'bg-red-600',
    brandColor: '#d91b24',
    officialCocUrl: 'https://www.airindia.com/content/dam/air-india/pdfs/air-india-coc.pdf',
    officialCharterUrl: 'https://www.airindia.com/content/dam/air-india/pdfs/passenger-charter-know-your-rights.pdf',
    officialSupportUrl: 'https://www.airindia.com/in/en/contact-us/customer-support-portal.html',
    nodalOfficer: {
      name: 'GM - Customer Relations & Nodal Officer',
      email: 'nodalofficer@airindia.com',
      phone: '011-69329333 / 011-69329999',
      address: 'Air India Customer Experience Team, Vatika One On One, Sector 16, Gurugram, Haryana - 122002',
      turnaround: 'Resolution within 10 business days',
    },
    appellateAuthority: {
      name: 'Executive Director - Customer Experience (Appellate)',
      email: 'appellateauthority@airindia.com',
      phone: '011-69329333',
      turnaround: 'Final disposal within 30 business days',
    },
    customerCare: {
      phone: '1860 233 1407 / 011 69329333',
      email: 'contactus@airindia.com',
      chatUrl: 'https://www.airindia.com/in/en/contact-us/customer-support-portal.html',
    },
  },
  vistara: {
    id: 'vistara',
    name: 'Vistara (Merged into Air India)',
    code: 'UK / AI 2xxx',
    tagline: 'Merged on Nov 12, 2024. Flights operate under Air India with AI 2xxx codes.',
    logoBg: 'bg-purple-900',
    brandColor: '#582c83',
    officialCocUrl: 'https://www.airindia.com/content/dam/air-india/pdfs/air-india-coc.pdf',
    officialCharterUrl: 'https://www.airindia.com/in/en/vistara-air-india-merger-faqs.html',
    officialSupportUrl: 'https://www.airindia.com/in/en/vistara-air-india-merger.html',
    nodalOfficer: {
      name: 'Air India Merger Nodal Desk',
      email: 'nodalofficer@airindia.com',
      phone: '011-69329333',
      address: 'Air India Merger Support, Vatika One On One, Gurugram, Haryana 122002',
      turnaround: 'Resolution within 10 business days',
    },
    appellateAuthority: {
      name: 'Air India Group Appellate Authority',
      email: 'appellateauthority@airindia.com',
      turnaround: 'Final decision within 30 business days',
    },
    customerCare: {
      phone: '+91 9289228888 (Legacy Support) / 011 69329333',
      email: 'custrelations@airvistara.com / contactus@airindia.com',
      chatUrl: 'https://www.airindia.com/in/en/vistara-air-india-merger-faqs.html',
    },
  },
  akasa: {
    id: 'akasa',
    name: 'Akasa Air (SNV Aviation Pvt Ltd)',
    code: 'QP',
    tagline: "India's newest greenest low-fare commercial airline",
    logoBg: 'bg-orange-500',
    brandColor: '#ff6200',
    officialCocUrl: 'https://www.akasaair.com/quick-links/conditions-of-carriage',
    officialCharterUrl: 'https://www.akasaair.com/customer-support/grievance-redressal-process',
    officialSupportUrl: 'https://www.akasaair.com/customer-support',
    nodalOfficer: {
      name: 'Nodal Officer - Grievance Redressal',
      email: 'nodalofficer@akasaair.com',
      phone: '+91 9606 112131',
      address: 'SNV Aviation Pvt Ltd, Urmi Estate, Tower A, 9th Floor, 95 Ganpatrao Kadam Marg, Lower Parel, Mumbai 400013',
      turnaround: 'Resolution within 10 business days',
    },
    appellateAuthority: {
      name: 'Appellate Authority',
      email: 'appellateauthority@akasaair.com',
      turnaround: 'Final appellate order within 30 business days',
    },
    customerCare: {
      phone: '+91 9606 112131',
      email: 'support@akasaair.com',
      chatUrl: 'https://www.akasaair.com/customer-support',
    },
  },
  aix: {
    id: 'aix',
    name: 'Air India Express (inc. AirAsia India / AIX Connect)',
    code: 'IX',
    tagline: 'Low-cost subsidiary of Air India with unified domestic & regional network',
    logoBg: 'bg-amber-600',
    brandColor: '#e05a10',
    officialCocUrl: 'https://www.airindiaexpress.com/tnc',
    officialCharterUrl: 'https://www.airindiaexpress.com/passenger-rights',
    officialSupportUrl: 'https://www.airindiaexpress.com/support',
    nodalOfficer: {
      name: 'Nodal Grievance Officer',
      email: 'nodalofficer@airindiaexpress.com',
      phone: '080-46662222 / 080-67662222',
      address: 'Air India Express Headquarters, Sector 21, Gurugram, Haryana, India',
      turnaround: 'Resolution within 10 business days',
    },
    appellateAuthority: {
      name: 'Appellate Authority for Consumer Claims',
      email: 'appellateauthority@airindiaexpress.com',
      turnaround: 'Appeal review within 30 business days',
    },
    customerCare: {
      phone: '+91 80 4666 2222 / +91 80 6766 2222',
      email: 'customersupport@airindiaexpress.com',
      chatUrl: 'https://www.airindiaexpress.com/support',
    },
  },
  spicejet: {
    id: 'spicejet',
    name: 'SpiceJet Airlines',
    code: 'SG',
    tagline: "India's pioneer budget carrier connecting tier-2 & tier-3 destinations",
    logoBg: 'bg-red-700',
    brandColor: '#ed1b24',
    officialCocUrl: 'https://corporate.spicejet.com/Tnc.aspx',
    officialCharterUrl: 'https://corporate.spicejet.com/PassengerSupport.aspx',
    officialSupportUrl: 'https://corporate.spicejet.com/ContactUs.aspx',
    nodalOfficer: {
      name: 'Nodal Officer - Customer Relations',
      email: 'nodalofficer@spicejet.com',
      phone: '+91 124 4983410 / +91 124 7101600',
      address: 'SpiceJet Ltd., 319, Udyog Vihar, Phase IV, Gurugram, Haryana - 122016, India',
      turnaround: 'Resolution within 10 business days',
    },
    appellateAuthority: {
      name: 'Appellate Authority',
      email: 'appellateauthority@spicejet.com',
      phone: '+91 124 4983410',
      turnaround: 'Final appeal decision within 30 business days',
    },
    customerCare: {
      phone: '+91 124 4983410 / +91 96540 03333',
      email: 'custrelations@spicejet.com',
      chatUrl: 'https://www.spicejet.com',
    },
  },
};

export const EXTERNAL_AUTHORITIES = {
  airSewa: {
    name: 'AirSewa (Ministry of Civil Aviation)',
    description: 'Central Government Grievance Redressal Portal for all civil aviation passengers in India.',
    url: 'https://airsewa.gov.in',
    tollFree: '1800 11 0031',
    mobileApp: 'AirSewa iOS & Android app',
  },
  nch: {
    name: 'National Consumer Helpline (NCH)',
    description: 'Department of Consumer Affairs, Government of India for unfair trade practices & deficiency of service.',
    url: 'https://consumerhelpline.gov.in',
    tollFree: '1915 or 1800-11-4000',
    sms: 'SMS 8800001915',
  },
  edaakhil: {
    name: 'e-Daakhil Portal (Consumer Forum & Court)',
    description: 'Direct online filing of consumer disputes before District, State and National Consumer Disputes Redressal Commissions (NCDRC) under Consumer Protection Act 2019 without hiring a lawyer.',
    url: 'https://edaakhil.nic.in',
  },
  dgcaSugam: {
    name: 'DGCA Sugam Portal',
    description: 'Directorate General of Civil Aviation portal for passenger regulatory reporting.',
    url: 'https://eseva.dgca.gov.in',
  },
};
