import { AirlineId, AirlineInfo } from './types';

export const AIRLINE_DIRECTORY: Record<AirlineId, AirlineInfo> = {
  indigo: {
    id: 'indigo',
    name: 'IndiGo (InterGlobe Aviation Ltd)',
    shortName: 'IndiGo',
    code: '6E',
    logoUrl: '/airlines/indigo.png',
    tagline: 'Low-cost airline with largest domestic market share',
    logoBg: 'bg-blue-600',
    officialCocUrl: 'https://www.goindigo.in/information/conditions-of-carriage.html',
    officialCharterUrl: 'https://www.goindigo.in/information/passenger-charter.html',
    officialSupportUrl: 'https://www.goindigo.in/contact-us.html',
    nodalOfficer: {
      email: 'nodalofficer@goindigo.in',
      phone: '+91 124 6173838',
      address: 'Central Wing, Ground Floor, Thapar House, 124 Janpath, New Delhi 110001',
    },
    appellateAuthority: {
      email: 'appellateauthority@goindigo.in',
    },
    customerCare: {
      phone: '+91 9910 383838',
      email: 'customer.relations@goindigo.in',
    },
  },
  airindia: {
    id: 'airindia',
    name: 'Air India',
    shortName: 'Air India',
    code: 'AI',
    logoUrl: '/airlines/airindia.png',
    tagline: 'Flag carrier full-service airline (Tata Group)',
    logoBg: 'bg-red-600',
    officialCocUrl: 'https://www.airindia.com/content/dam/air-india/pdfs/air-india-coc.pdf',
    officialCharterUrl: 'https://www.airindia.com/content/dam/air-india/pdfs/passenger-charter-know-your-rights.pdf',
    officialSupportUrl: 'https://www.airindia.com/in/en/contact-us/customer-support-portal.html',
    nodalOfficer: {
      email: 'nodalofficer@airindia.com',
      phone: '011-69329333',
      address: 'Air India Customer Experience Team, Vatika One On One, Sector 16, Gurugram 122002',
    },
    appellateAuthority: {
      email: 'appellateauthority@airindia.com',
    },
    customerCare: {
      phone: '1860 233 1407 / 011 69329333',
      email: 'contactus@airindia.com',
    },
  },
  vistara: {
    id: 'vistara',
    name: 'Vistara (Merged with Air India)',
    shortName: 'Vistara',
    code: 'UK / AI 2xxx',
    logoUrl: '/airlines/vistara.png',
    tagline: 'Merged into Air India (Nov 2024), operating under AI 2xxx flight codes',
    logoBg: 'bg-purple-900',
    officialCocUrl: 'https://www.airindia.com/content/dam/air-india/pdfs/air-india-coc.pdf',
    officialCharterUrl: 'https://www.airindia.com/in/en/vistara-air-india-merger-faqs.html',
    officialSupportUrl: 'https://www.airindia.com/in/en/vistara-air-india-merger.html',
    nodalOfficer: {
      email: 'nodalofficer@airindia.com',
      phone: '011-69329333',
      address: 'Air India Vatika One On One, Gurugram, Haryana 122002',
    },
    appellateAuthority: {
      email: 'appellateauthority@airindia.com',
    },
    customerCare: {
      phone: '+91 9289228888 / 011 69329333',
      email: 'contactus@airindia.com',
    },
  },
  akasa: {
    id: 'akasa',
    name: 'Akasa Air (SNV Aviation)',
    shortName: 'Akasa Air',
    code: 'QP',
    logoUrl: '/airlines/akasa.png',
    tagline: "India's newest greenest low-fare airline",
    logoBg: 'bg-orange-500',
    officialCocUrl: 'https://www.akasaair.com/quick-links/conditions-of-carriage',
    officialCharterUrl: 'https://www.akasaair.com/customer-support/grievance-redressal-process',
    officialSupportUrl: 'https://www.akasaair.com/customer-support',
    nodalOfficer: {
      email: 'nodalofficer@akasaair.com',
      phone: '+91 9606 112131',
      address: 'SNV Aviation, Urmi Estate, Tower A, Lower Parel, Mumbai 400013',
    },
    appellateAuthority: {
      email: 'appellateauthority@akasaair.com',
    },
    customerCare: {
      phone: '+91 9606 112131',
      email: 'support@akasaair.com',
    },
  },
  aix: {
    id: 'aix',
    name: 'Air India Express (inc. AirAsia India)',
    shortName: 'AI Express',
    code: 'IX',
    logoUrl: '/airlines/aix.png',
    tagline: 'Low-cost airline of Tata Group with unified domestic routes',
    logoBg: 'bg-amber-600',
    officialCocUrl: 'https://www.airindiaexpress.com/tnc',
    officialCharterUrl: 'https://www.airindiaexpress.com/passenger-rights',
    officialSupportUrl: 'https://www.airindiaexpress.com/support',
    nodalOfficer: {
      email: 'nodalofficer@airindiaexpress.com',
      phone: '080-46662222',
      address: 'Air India Express HQ, Sector 21, Gurugram, Haryana',
    },
    appellateAuthority: {
      email: 'appellateauthority@airindiaexpress.com',
    },
    customerCare: {
      phone: '+91 80 4666 2222',
      email: 'customersupport@airindiaexpress.com',
    },
  },
  spicejet: {
    id: 'spicejet',
    name: 'SpiceJet Airlines',
    shortName: 'SpiceJet',
    code: 'SG',
    logoUrl: '/airlines/spicejet.png',
    tagline: 'Budget airline connecting tier-2 & tier-3 destinations',
    logoBg: 'bg-red-700',
    officialCocUrl: 'https://corporate.spicejet.com/Tnc.aspx',
    officialCharterUrl: 'https://corporate.spicejet.com/PassengerSupport.aspx',
    officialSupportUrl: 'https://corporate.spicejet.com/ContactUs.aspx',
    nodalOfficer: {
      email: 'nodalofficer@spicejet.com',
      phone: '+91 124 4983410',
      address: 'SpiceJet Ltd, 319 Udyog Vihar, Phase IV, Gurugram 122016',
    },
    appellateAuthority: {
      email: 'appellateauthority@spicejet.com',
    },
    customerCare: {
      phone: '+91 124 4983410',
      email: 'custrelations@spicejet.com',
    },
  },
};
